### ISSUE TITLE
Exception during validation

### ISSUE THREAD

**Issue by pkaczynski** [conda-incubator/conda-mirror#23]
Validation steps always ends like this. Is python 3.8 supported?
```
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\programdata\miniconda3\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "c:\programdata\miniconda3\lib\site-packages\conda_mirror\conda_mirror.py", line 650, in _validate_or_remove_package
    logger.info('Validating {:4d} of {:4d}: {}.'.format(num + 1, num_packages,
AttributeError: 'NoneType' object has no attribute 'info'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\conda-mirror.exe\__main__.py", line 7, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\conda_mirror\conda_mirror.py", line 350, in cli
    main(**_parse_and_format_args())
  File "c:\programdata\miniconda3\lib\site-packages\conda_mirror\conda_mirror.py", line 879, in main
    validation_results = _validate_packages(packages, download_dir,
  File "c:\programdata\miniconda3\lib\site-packages\conda_mirror\conda_mirror.py", line 604, in _validate_packages
    validation_results = p.map(_validate_or_remove_package,
  File "c:\programdata\miniconda3\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\programdata\miniconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'info'
```

**Comment by HagegeR** [comment]
I got this too, try --num-threads 1, the problem is with the multi threading

**Comment by analog-cbarber** [comment]
I don't have a Windows machine to test this on, but was this fixed (or at least worked around) in https://github.com/conda-incubator/conda-mirror/commit/4ff5189820d56db9968d48b634ecf699d974b135?
